### ISSUE TITLE
CI: Python version

### ISSUE THREAD

**Issue by chraibi** [PedestrianDynamics/pedestrian-trajectory-analyzer#109]
[CI](https://github.com/PedestrianDynamics/pedestrian-trajectory-analyzer/blob/main/.github/workflows/ci.yml#L79) is using Python 3.8.

Should we move forward with a newer version? (3.9 or even 3.10)

**Comment by schroedtert** [comment]
No, Python 3.8 is widely used and Python 3.9/3.10 can use a 3.8 library
