### ISSUE TITLE
Behavior of get unit

### ISSUE THREAD

**Issue by chraibi** [PedestrianDynamics/pedestrian-trajectory-analyzer#93]
This [function](https://github.com/PedestrianDynamics/pedestrian-trajectory-analyzer/blob/main/analyzer/io/trajectory_parser.py#L181)
assumes that units are in meter (L194) and tries to parse this information from the file.

1. Some experiments are in cm *and* do not have any header. What does the function return in this case?
2. The expected header in this function does not cover some experiments with the following header
`# <number> <frame> <x> [in m] <y> [in m] <z> [in m]`

Suggestion: Make the parsing explicit:

1. If meter is found in header -> meter
2. If centimeter is found in header -> centimeter
3. if nothing found -> error and ask user for input

**Comment by schroedtert** [comment]
Closed with #103
