### ISSUE TITLE
Empty trajectories

### ISSUE THREAD

**Issue by chraibi** [PedestrianDynamics/pedestrian-trajectory-analyzer#94]
In this [line](https://github.com/PedestrianDynamics/pedestrian-trajectory-analyzer/blob/main/analyzer/io/trajectory_parser.py#L88) `data` are checked if they are empty. 
However, a couple of lines before `data` are used. 

Should the empty-check be used before accessing the data?

**Comment by schroedtert** [comment]
Closed with #103
